language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: jennastephens-github
    token:
      secure: 78e2e1a25f63ce571a9cbb3cf9637f19d38b1f1c
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
